// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvbTu4s54bvuE3g87v1fYak1w61EwL1g8',
    appId: '1:704633042290:web:ec001cf81c0630589499eb',
    messagingSenderId: '704633042290',
    projectId: 'master-calculator-pro2',
    authDomain: 'master-calculator-pro2.firebaseapp.com',
    databaseURL: 'https://master-calculator-pro2-default-rtdb.firebaseio.com',
    storageBucket: 'master-calculator-pro2.appspot.com',
    measurementId: 'G-43ZNY546SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWueP6whUFM8q_czfvtURGA0yqW3rKm40',
    appId: '1:704633042290:android:0e26d1fabd028d719499eb',
    messagingSenderId: '704633042290',
    projectId: 'master-calculator-pro2',
    databaseURL: 'https://master-calculator-pro2-default-rtdb.firebaseio.com',
    storageBucket: 'master-calculator-pro2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0eRebk7cdCA2FMBsIwuRIfdOlmZX4Eg',
    appId: '1:704633042290:ios:673c43ae319d95779499eb',
    messagingSenderId: '704633042290',
    projectId: 'master-calculator-pro2',
    databaseURL: 'https://master-calculator-pro2-default-rtdb.firebaseio.com',
    storageBucket: 'master-calculator-pro2.appspot.com',
    androidClientId: '704633042290-15jh5oio6qh3bdavc88q2ru7tn1ppvvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackerspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0eRebk7cdCA2FMBsIwuRIfdOlmZX4Eg',
    appId: '1:704633042290:ios:673c43ae319d95779499eb',
    messagingSenderId: '704633042290',
    projectId: 'master-calculator-pro2',
    databaseURL: 'https://master-calculator-pro2-default-rtdb.firebaseio.com',
    storageBucket: 'master-calculator-pro2.appspot.com',
    androidClientId: '704633042290-15jh5oio6qh3bdavc88q2ru7tn1ppvvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackerspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvbTu4s54bvuE3g87v1fYak1w61EwL1g8',
    appId: '1:704633042290:web:6e29ebc44e5cb40b9499eb',
    messagingSenderId: '704633042290',
    projectId: 'master-calculator-pro2',
    authDomain: 'master-calculator-pro2.firebaseapp.com',
    databaseURL: 'https://master-calculator-pro2-default-rtdb.firebaseio.com',
    storageBucket: 'master-calculator-pro2.appspot.com',
    measurementId: 'G-RGJXS5G8RY',
  );

}